### ISSUE TITLE
Using example code, SubmissionStream not working

### ISSUE THREAD

**Issue by TadeoKondrak** [MayorMonty/Snoostorm#1]
it doesn't trigger on any type of post, link or text.

**Comment by TadeoKondrak** [comment]
actually, it's just the example code is wrong. 

`submissionStream.on("comment", function(post) {
  console.log(`New submission by ${post.author.name}`);
});`
should be 
`submissionStream.on("submission", function(post) {
  console.log(`New submission by ${post.author.name}`);
});`

**Comment by MayorMonty** [comment]
Oh geez, didn't event see that! Sorry!
