### ISSUE TITLE
Required TypeScript fields in package.json

### ISSUE THREAD

**Issue by sabbatiw** [MayorMonty/Snoostorm#12]
The `package.json` file for a TypeScript module requires both a `"main"` field and a "`types`" field.

For this package I believe they should be set to the following:
`"main": "out/main.js",`
`"types": "out/main.d.ts"`

Without these two fields set correctly, Node.js throws the following error when attempting to `require('snoostorm')`:
*`Error: Cannot find module 'snoostorm'`*.

**Comment by MayorMonty** [comment]
This is why you do thorough testing before publishing new versions instead of just pushing things. Go ahead and make a pull! Thanks

**Comment by MayorMonty** [comment]
Fixed in 8f9bb74b52b98a84968f3c0cd8610488711fa4ff
