### ISSUE TITLE
TypeError: Snoostorm is not a constructor

### ISSUE THREAD

**Issue by cherryblossom000** [MayorMonty/Snoostorm#14]
I used [this tutorial](https://blog.syntonic.io/2017/07/07/reddit-bot-nodejs-example) to set up a Reddit bot. This is my code so far:
```js
//modules
require('dotenv').config();
const Snoowrap = require('snoowrap');
const Snoostorm = require('snoostorm');

//clients
const r = new Snoowrap({
	userAgent: 'some-description',
	clientId: process.env.CLIENT_ID,
	clientSecret: process.env.CLIENT_SECRET,
	username: process.env.REDDIT_USER,
	password: process.env.REDDIT_PASS
});
const client = new Snoostorm(r);

//options and stream
const streamOpts = {
	subreddit: 'all',
	results: 25
};
const comments = client.CommentStream(streamOpts);

comments.on('comment', (comment) => {
	console.log(comment);
});
```

However, when I run it I get this error:
```
const client = new Snoostorm(r);
               ^

TypeError: Snoostorm is not a constructor
    at Object.<anonymous> (/Users/myname/Documents/GitHub/repo-name/server.js:14:16)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by MayorMonty** [comment]
Yeah that tutorial is outdated (I've tried contacting the author to get him to update, but he hasn't responded to me)

The correct usage should be:
```javascript

const { CommentStream } = require("snoostorm");

require('dotenv').config();
const Snoowrap = require('snoowrap');
const Snoostorm = require('snoostorm');

const r = new Snoowrap({
	userAgent: 'some-description',
	clientId: process.env.CLIENT_ID,
	clientSecret: process.env.CLIENT_SECRET,
	username: process.env.REDDIT_USER,
	password: process.env.REDDIT_PASS
});

const stream = new CommentStream(r, { subreddit: "all", results: 25 });

stream.on("item", comment => {
    console.log(comment)
})

```

Thanks for using Snoostorm!

**Comment by cherryblossom000** [comment]
Thanks!

**Comment by k3n** [comment]
Found this since I was having the same error from the same blog post :D

I followed the suggestion, but now it's complaining about the `results: 25`:

```
Argument of type '{ subreddit: string; results: number; }' is not assignable to parameter of type 'SnooStormOptions'.
  Object literal may only specify known properties, and 'results' does not exist in type 'SnooStormOptions'.ts(2345)
```

I changed that to `limit: 25` per this project's `readme.md` and the squiggles went away. Just a note for future visitors.

**Comment by MayorMonty** [comment]
Yes, the article is completely outdated. I've reached out to the author trying to get him to update but I haven't heard back (and as a side note, the GitHub repo seems to have been compromised)

I'm really busy these days, but if one of you wants to work with me to make a very quick usage tutorial, I'd love to merge it here

**Comment by 13thontheleft** [comment]
The revised example to correct this error gives me:

`(node:9182) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: array.map is not a function
(node:9182) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9182) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: array.map is not a function`

am I doing it wrong?
