### ISSUE TITLE
Adding support for modmails

### ISSUE THREAD

**Issue by MilkGames** [MayorMonty/Snoostorm#18]
**Is your feature request related to a problem? Please describe.**
I'd like to automate some flows within Modmails.

**Describe the solution you'd like**
The ability to get streams of modmails (The new modmail - not the old)

**Describe alternatives you've considered**
N/A

**Additional context**
https://not-an-aardvark.github.io/snoowrap/ModmailConversation.html

**Comment by MayorMonty** [comment]
This should be pretty quick to implement. If you want to take the lead, that would be fantastic! The most relevant decision you'll have to make is how to distinguish different modmail conversations (maybe compare the JSON object?)

I've set up the `Poll` class such that it's very very easy to extend and add new streams

**Comment by MayorMonty** [comment]
I've gone ahead and implemented a very basic version of `ModMailStream` (without any testing 😃) in `snoowrap@1.1.2`, see if you can stress test in for your purposes.

**Comment by MilkGames** [comment]
Hey there, I have updated to the latest version however I am getting the `TypeError: ModMailStream is not a constructor` error. After looking at your code, I believe you're using the old modmail.

You should be using something like this:
`
r.getNewModmailConversations({limit: 2}).then(console.log)`

**Comment by MayorMonty** [comment]
Upgraded snoowrap to the newest version to get new method. The new version should be working correctly, I've tested it successfully on my test servers, but I don't moderate any larger subreddits which would be better test grounds
