### ISSUE TITLE
Fetches older post as new when a post is removed.

### ISSUE THREAD

**Issue by fuzzfactory0** [MayorMonty/Snoostorm#19]
**Describe the bug**
Every time a post is deleted from the subreddit you're watching, the Xth post on the subreddit will get reposted in your feed (Assuming X is the number of results configured in your code.)

**To Reproduce**
1. Submit more posts than the "results" config to a subreddit you're watching
2. Remove the latest post
3. See error

**Expected behavior**
Nothing. When a post is removed, it should do nothing.

**Additional context**
This happens because of how new posts are detected by comparing batches and removing duplicates. When a post is removed, the new batch will have an older post than every post in the previous batch, and that one is treated as new by the code.
Easy fix: compare timestamps between posts.

**Comment by MayorMonty** [comment]
Generally, there are a lot of unexpected behaviors that can come from setting `results` too low. Is snoostorm reissuing new events for posts it has handled in the past? Cause that is aberrant behavior. For now, until I can properly triage, setting `results` higher (usually 25 posts is good for all of reddit)

**Comment by MayorMonty** [comment]
So far, I've been unable to replicate this issue. Can you give me a minimal verified example?

**Comment by MayorMonty** [comment]
Cannot replicate, see if this issue is still a problem with `snoostorm@1.4.0`
