### ISSUE TITLE
Add the ability to get a stream of a user's posts and comments

### ISSUE THREAD

**Issue by scratchyone** [MayorMonty/Snoostorm#22]
**Is your feature request related to a problem? Please describe.**
Afaik there isn't any way to access a stream of a user's new posts and comments.

**Describe the solution you'd like**
User's posts and comments should be accessible like subreddits:
```
const comments = new CommentStream(client, { user: "ExampleUser", limit: 10, pollTime: 2000 });
comments.on("item", console.log);

const submissions = new SubmissionStream(client, { user: "ExampleUser", limit: 10, pollTime: 2000 });
submissions.on("item", console.log);
```

**Describe alternatives you've considered**
I've used snoowrap to poll a user's posts and comments every few seconds

**Comment by MayorMonty** [comment]
Currently, the way to get a specific users post is with [`RedditUser#getSubmissions`](https://not-an-aardvark.github.io/snoowrap/RedditUser.html#getSubmissions__anchor). Because that's a different function call, idk if having a `user` option is the best, but it does create a very nice abstraction.
