### ISSUE TITLE
Error handling?

### ISSUE THREAD

**Issue by gc** [MayorMonty/Snoostorm#23]
Hi!

I have a question regarding error handling. How do you recommend to do this? I occasionally get 401 errors, and am not sure how I should catch them. Thanks!

**Comment by MayorMonty** [comment]
Events *should* bubble up through the call stack, and as such `try/catch` or promise `.catch()` is going to be your best bet. Currently I'm not exposing the raw requests on the `Poll` parent class, but I imagine that could be a feature in the future

**Comment by MayorMonty** [comment]
Events *should* bubble up through the call stack, and as such `try/catch` or promise `.catch()` is going to be your best bet. Currently I'm not exposing the raw requests on the `Poll` parent class, but I imagine that could be a feature in the future
