### ISSUE TITLE
Could not find a declaration file for module 'snoostorm'

### ISSUE THREAD

**Issue by jasonharrison** [MayorMonty/Snoostorm#26]
**Describe the bug**
After upgrading to 1.2.1, no typings are found.

**To Reproduce**
Install snoostorm@1.2.1 and attempt to use with TypeScript.

**Expected behavior**
Typings should exist.

**Actual behavior**
```Could not find a declaration file for module 'snoostorm'```

**System Configuration:**
Using TypeScript? Yes, 3.6.2
Node Version? 11.15.0
Snoostorm Version? 1.2.1

**Comment by MayorMonty** [comment]
Fixed in [1.2.2](https://www.npmjs.com/package/snoostorm/v/1.2.2). Forgot to bundle generated types with NPM. Sorry about that!

**Comment by jasonharrison** [comment]
Wow you're quick!  Thanks.
