### ISSUE TITLE
Very long delay for replies to register on reddit.

### ISSUE THREAD

**Issue by ExtendedInterlude** [MayorMonty/Snoostorm#27]
**Describe the bug**
Not sure on what exactly the bug is but there is a huge delay (>50 minutes) in replies registering (displaying in the post comments, displaying in inbox, displaying in overview, etc) on reddit. This occurs within 5 minutes of starting the streams. There is also a delay in saving comments and submissions. This is not affecting retrieving comments.

**To Reproduce**
Run this code, let it sit for around 5 or more minutes, then trigger the streams with comments or posts.

    const client: Snoowrap = new Snoowrap({
        userAgent: process.env.USER_AGENT,
        clientId: process.env.CLIENT_ID,
        clientSecret: process.env.CLIENT_SECRET,
        username: process.env.REDDIT_USER,
        password: process.env.REDDIT_PASS
    });
    client.config({ continueAfterRatelimitError: true, requestDelay: 2000 });

    const comments: CommentStream = new CommentStream(client, { subreddit: '<name>', limit: 100 });
    comments.on('item', (comment: Comment): void => {
        if (!comment.saved && comment.author.name !== BOT_NAME) {
            // Just constructs a string for the reply and could just be const reply: string = 'foo';.
            const reply: string = getReply(comment);
            if (reply) {
                comment.reply(reply);
                comment.save();
            }
        }
    });

    const submissions: SubmissionStream = new SubmissionStream(client, { subreddit: '<name>', limit: 100 });
    submissions.on('item', (submission: Submission) => { // Same as CommentStream. });

**Expected behavior**
The replies later in the streams' uptimes registering on reddit as quickly as in the beginning.

**System Configuration:**
TypeScript - 3.6.4
Node Version - 12.13.0
Snoostorm Version - 1.2.2
Snoowrap Version - 1.20.0 

**Additional context**
I have this running on both a Linux EC2 instance and a personal Windows 7 machine. The delays occur on both machines. As for snoowrap config options and snoostorm stream options, I tried `continueAfterRatelimitError` and `requestDelay` with various combinations of  `limit` and `pollTime`.

**Comment by MayorMonty** [comment]
Cannot replicate. Make sure that you're not being ratelimited, as `snoowrap` will automatically respect ratelimits.
