### ISSUE TITLE
ModMailStream not firing on new mod mail

### ISSUE THREAD

**Issue by kyleratti** [MayorMonty/Snoostorm#36]
**Describe the bug**
After setting up a ModMailStream using mod credentials and adding a listener for `.on("item", (item) => console.log)` and having new messages sent in modmail, I am not seeing the callback fire.

**To Reproduce**
Run the code below:

```typescript
import { ModMailStream } from "snoostorm";
import { redditapi } from "./services/redditapi";
import snoowrap from "snoowrap";

const redditapi = new snoowrap({
  userAgent: process.env.REDDIT_USER_AGENT,
  clientId: process.env.REDDIT_CLIENTID,
  clientSecret: process.env.REDDIT_CLIENTSECRET,
  username: process.env.REDDIT_USERNAME,
  password: process.env.REDDIT_PASSWORD,
});

redditapi.getModmail().then((messages) => {
  console.log(messages);
});

const modListener = new ModMailStream(redditapi, {
  pollTime: 1000, // FIXME: use environment variable
});

modListener.on("item", (item) => console.log(item));
modListener.on("listing", (items) => {
  if (items.length > 0) console.log(items);
});
```

It does successfully retrieve 25 modmail messages on startup, and it does keeping firing the `"listing"` event listeners with an empty array, however neither the `"item"` or `"listing"` listeners fire with mod mail despite a handful of messages arriving since startup.

**Expected behavior**
New mod mail messages should be fired into the listener

**System Configuration:**
Using TypeScript? `v3.9.5`
Node Version? `v12.16.3`
Snoostorm Version? `v1.4.2`

**Additional context**
Not sure if I just missed something in the docs. Thank you.

**Comment by MayorMonty** [comment]
I was calling the wrong get method! This is fixed in [`snoowrap@1.5.0`](https://npm.im/snoowrap).

Fixed in 352a714b79a684de0c9931e0f582b3e426b1f185

**Comment by MayorMonty** [comment]
Note that this update changes the types of the `ModMailStream` events from [`ModmailConversation`](https://not-an-aardvark.github.io/snoowrap/ModmailConversation.html) to [`PrivateMessage`](https://not-an-aardvark.github.io/snoowrap/PrivateMessage.html)

Additionally, it's important to remember that private message listeners will also get mod mail conversations

**Comment by kyleratti** [comment]
Wow - that was fast. Happens to the best of us, thanks @MayorMonty!

This library is the backbone of tuckbot and now modmail-manager. 🥳
