### ISSUE TITLE
can't use r/all

### ISSUE THREAD

**Issue by JeffaloBob** [MayorMonty/Snoostorm#37]
**Describe the bug**
when i give a comment stream `all` as the subreddit it doesn't get anything, while if i do `askreddit` i'll get a lot of things

**To Reproduce**
1. use this code with a snoowrap client called client
```
const comments = new CommentStream(client, {
  subreddit: "all",
  limit: 10,
  pollTime: 2000,
});
```
2. run
3. it doesnt work
**Expected behavior**
It will get a bunch of posts from r/all

**System Configuration:**
Using TypeScript?
no
Node Version?
` node: '12.14.1',`
Snoostorm Version?
^1.5.0
Snoowrap Version?
1.21.0
**Additional context**
I didn't do anything and it just stopped working? is this a reddit api thing?

**Comment by MayorMonty** [comment]
Cannot replicate, make sure you are correctly authenticated and you have not exceeded your ratelimit.
