### ISSUE TITLE
TypeError: client.getNewComments is not a function

### ISSUE THREAD

**Issue by thetayloredman** [MayorMonty/Snoostorm#39]
**Describe the bug**
I can't launch bot
`(node:23869) UnhandledPromiseRejectionWarning: TypeError: client.getNewComments is not a function`

**To Reproduce**

1. turn on bot
2. get `(node:23869) UnhandledPromiseRejectionWarning: TypeError: client.getNewComments is not a function`

**Expected behavior**
Bot to turn on

**System Configuration:**
Using TypeScript? no
Node Version? latest
Snoostorm Version? latest
Snoowrap Version? latest

**Additional context**
here is my code

```
// ----- PACKAGES -----
const { CommentStream, InboxStream, SubmissionStream } = require("snoostorm")
const Snoowrap = require("snoowrap") // Snoowrap is the reddit API
const Snoostorm = require("snoostorm") // Reads comments/posts

// ----- FILE IMPORTS -----
const config = require("./config.json")

// ----- VARIABLES -----

// ----- BOT SETUP -----
const client = config.credentials

const streamOpts = {
    subreddit: config.subreddit,
    results: 25
};

const stream = new CommentStream(streamOpts);

// ----- BOT LISTENER -----

stream.on('comment', (comment) => {
    console.log('New comment: ' + comment);
});```

**Comment by MayorMonty** [comment]
You need to pass your instance of snoowrap to `CommentStream`.

**Comment by thetayloredman** [comment]
Fixed, but now im not getting any logs for comments
