### ISSUE TITLE
Never triggers, using example code

### ISSUE THREAD

**Issue by austinhuang0131** [MayorMonty/Snoostorm#4]
```js
require('dotenv').config();

const Snoowrap = require('snoowrap');
const Snoostorm = require('snoostorm');

const r = new Snoowrap({
    userAgent: 'nodejs:redditinsurance:v1.0.0 (by u/austinhuang)',
    clientId: process.env.CLIENT_ID,
    clientSecret: process.env.CLIENT_SECRET,
    username: process.env.REDDIT_USER,
    password: process.env.REDDIT_PASS
});
const client = new Snoostorm(r);

var comments = client.CommentStream({
	subreddit: "all",
	results: 1000,
	pollTime: 3000
});

comments.on('comment', (comment) => {
    if (comment.body === 'I\'d like to start a claim.') {
		return r.getSubmission(comment.link_id).fetch().then(post => {
			return comment.reply('Your claim has been submitted. We\'ll get back to you once it is processed.\n\nBest Regards, Reddit Insurance^[Info](https://reddit.com/r/RedditInsurance)');
		});
    }
});```

**Comment by MayorMonty** [comment]
Can't test this now, what's the output/error?

**Comment by austinhuang0131** [comment]
There is no output<sup>aside from the "you are being ratelimited" thingy</sup>, it just doesn't do anything.

**Comment by MayorMonty** [comment]
If you're getting rate limiting errors, then it sounds like you haven't corrected configured your bot account. Depending on the exact error message, you may be unable to make posts/read data because of karma restrictions. You can remove these restrictions by making the bot accounts moderators on the applicable subreddit. However, I can't really help you unless you give me the exact output when the code is executed

**Comment by austinhuang0131** [comment]
Since I left Snoostorm already (Basically setInterval to fetch posts), I cannot retest it (I can only do stuff on my borrowed VPS which I can't use it for testing, I can only use it for production. Plus, my own PC is admin-locked thus I can't get nodejs). I think there was no output log aside from ratelimiting (by Snoowrap).

**Comment by MayorMonty** [comment]
Be wary of duplicate responses when using setInterval; snoostorm had a system to ensure that handlers were never called more than once for one comment / post
