### ISSUE TITLE
RFC: Modularize API Library

### ISSUE THREAD

**Issue by brenapp** [MayorMonty/Snoostorm#42]
Currently, this project uses [`snoowrap`](https://github.com/not-an-aardvark/snoowrap) as it's API provider, as it remains the most popular library, and was pretty much the only one when I created this project.

Is there a need for other providers to be used? What providers should I consider adding?

**Comment by thetayloredman** [comment]
I can't think of any better providers personally

###### maybe a custom one? wink wink
