### ISSUE TITLE
Does this poll, or use the stream api?

### ISSUE THREAD

**Issue by kbirger** [MayorMonty/Snoostorm#45]
The description suggests that this uses streaming, which implies the use of a push api through websockets. However, there's a pollTime setting, which makes me think that this just polls periodically.

Which is the case?

**Comment by MayorMonty** [comment]
This library is poll-based using the snoowrap library. As far as I'm aware there is no first-party websocket based solution for all of the different constructs that snoostorm supports ([rockets](https://github.com/rockets/rockets) seems to serve a similar use case if you need a websocket).

**Comment by kbirger** [comment]
Thanks. Yeah, I don't think there's a full library for nodejs. I'm coming from reddit-stream, which is a small wrapper around raw.js which provides many reddit apis.

Nothing seems actually maintained anymore though.

Thanks for the tip

**Comment by FoxxMD** [comment]
@kbirger did you ever find an alternative?

**Comment by kbirger** [comment]
Nope
