### ISSUE TITLE
Unnecessary production dependency of Snyk

### ISSUE THREAD

**Issue by gc** [MayorMonty/Snoostorm#46]
Snyk is adding 3mb and 45 dependencies (and possibly much more transient deps) to the size of Snoostorm.

- This was fixed here: https://github.com/MayorMonty/Snoostorm/pull/25
- But Snyk has, for some reason, undone the fix and moved it back: https://github.com/MayorMonty/Snoostorm/commit/4151d0e9ea8db8527b309f4541db2892629e29b0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by MayorMonty** [comment]
Should be fixed in https://github.com/MayorMonty/Snoostorm/commit/812309242afc08c1a34cce9720341cd361c0704b. (npm version `1.5.1`)
