### ISSUE TITLE
Is it possible to scrape a keyword from a comment after entering a command?

### ISSUE THREAD

**Issue by JimmyPrice** [MayorMonty/Snoostorm#5]
For example !KEYWORD and Snoostorm would return KEYWORD. 
So far I have:

comments.on('comment', (comment, keyword) => {
    if (comment.body.includes("!" + keyword)) {
       //Do something with keyword
    } else{
        console.log("invalid keyword)
    }
});

I'd really appreciate some help, many thanks

**Comment by stoutlabs** [comment]
`comments.on("comment", (comment, keyword) => {  
  const commentArr = comment.body.split(" ");    
  if (commentArr.includes(keyword)) {
    console.log(`keyword found: ${keyword}`);
  } else {
    console.log("keyword was not in this comment.")
  }
});`

Something like that should do the trick! (You probably figured this out by now, but thought I would post a solution in case anyone else stops by.)

**Comment by MayorMonty** [comment]
Sorry that I've been unresponsive, school has really gotten to me, and open source project have had to go on the backburner. Thanks to @stoutlabs for fixing this issue
