### ISSUE TITLE
Snoostorm is not a constructor

### ISSUE THREAD

**Issue by haroongames-git** [MayorMonty/Snoostorm#50]
**Describe the bug**
When I try to do `new Snoostorm()`, I get an error saying Snoostorm is not a constructor.
When I try to use the Snoostorm constructor as a normal function, it also says it isn't a function?

**To Reproduce**

1. Initialize the library as usual.
2. Run code.
3. View error.

**Expected behavior**
The script runs successfully.

**System Configuration:**
Using TypeScript? No
Node Version? v12.18.3
Snoostorm Version? latest
Snoowrap Version? latest

**Additional context**
None.

**Comment by MayorMonty** [comment]
Cannot replicate, please post the code you are using

**Comment by haroongames-git** [comment]
> Cannot replicate, please post the code you are using

```js
const Snoowrap = require('snoowrap');
const Snoostorm = require('snoostorm');

// Build Snoowrap and Snoostorm clients
const r = new Snoowrap({
    userAgent: 'reddit-bot-example-node',
    clientId: process.env.CLIENT_ID,
    clientSecret: process.env.CLIENT_SECRET,
    username: process.env.REDDIT_USER,
    password: process.env.REDDIT_PASS
});
const client = new Snoostorm(r);```

**Comment by Keimeno** [comment]
There is no default export @haroongames-git you need to use one of snoostorms exported classes.
```js
const {
  CommentStream, 
  SubmissionStream, 
  InboxStream, 
  ModMailStream, 
  ModQueueStream, 
  Poll
} = require('snoostorm');
```

You can check the [source code](https://github.com/MayorMonty/Snoostorm/blob/master/src/main.ts) for more details

**Comment by Keimeno** [comment]
@MayorMonty I think this issue can be closed

**Comment by MayorMonty** [comment]
Thank you @Keimeno!
