### ISSUE TITLE
Get only unread messages in inbox stream/filtering the inbox

### ISSUE THREAD

**Issue by BassamHajjage** [MayorMonty/Snoostorm#52]
**Is your feature request related to a problem? Please describe.**
I found it difficult to find/apply the way to apply snoowrap's inbox filters to snoostorm's inbox stream

**Describe the solution you'd like**
I would love it if it was as easy as pie to use filters in the inbox stream, for example [like so](https://i.imgur.com/7ymmsCO.png).

**Describe alternatives you've considered**
Apparently, [snoostorm-es6](https://www.npmjs.com/package/snoostorm-es6/v/1.0.4) has this feature, but hasn't been updated in a while, so I'll simply use my own snoowrap function until this is fixed or further instructions are provided on how to resolve it.

**Additional context**
Otherwise, the library is stellar

**Comment by lock9** [comment]
I have the same issue. How did you solve it? I'm unable to get my private messages, I only get comments

**Comment by MayorMonty** [comment]
`InboxStream` is a thin wrapper around [`client.getInbox`](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#getInbox__anchor). You can use `unread` to only get unread items and then filter in the listener. 

```TypeScript
const items = new InboxStream(client, {
  filter: "unread",
});

items.on("item", item => {
  if (item instanceof PrivateMessage) {
    item.markAsRead();

    console.log(item.body);

  };
});

```
