### ISSUE TITLE
Ratelimited always

### ISSUE THREAD

**Issue by geronimostar** [MayorMonty/Snoostorm#53]
I always get a ratelimit after replying using item.reply. how to fix?

**Comment by MayorMonty** [comment]
The current rate of polling for Snoostorm (once every 2 seconds) is designed to mostly saturate your rate limit (having a comment stream and submission stream simultaneously completely saturates it). You can reduce the poll rate by increasing the `pollTime` option in the `SnooStormOptions`

```TypeScript
const post = new CommentStream(client, {
  subreddit: "all",
  limit: 50,
  pollTime: 5000
});

post.on("item", (item) =>
  item.body.length > 1000 ? null : console.log(item.body)
);

setTimeout(() => post.end(), 1000 * 60 * 60);
```
