### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by JorensM** [MayorMonty/Snoostorm#55]
Hello, I would really like to use this library but couldn't find any documentation beyond the basic usage in the readme. Could anyone point me to some resources where I could learn to use this library?

**Comment by MayorMonty** [comment]
Honestly, there isn't a whole lot of documentation. This is something I am working on, but I'm a busy college student so my free time is severely limited 😉 

I would recommend looking at the source code, and the example usage. Additionally, make use of the TypeScript types to gett better editor reccomendations

**Comment by JorensM** [comment]
Thanks for responding, I'll check out the source code!
