### ISSUE TITLE
Config is not getting set with Snoostorm

### ISSUE THREAD

**Issue by Ishneetkaur** [MayorMonty/Snoostorm#7]
Using the following code
```
const r = new Snoowrap({
    userAgent: USER_AGENT,
    clientId: CLIENT_ID,
    clientSecret: CLIENT_SECRET,
    username: USERNAME,
    password: PASSWORD
});

r.config({continueAfterRatelimitError: true});

const client = new Snoostorm(r);
stream = client.SubmissionStream({
     subreddit: subreddits,
      results: 10,
      pollTime: 1000
});
stream.on('submission', (data) => {
 // data has continueAfterRatelimitError as false.
});
```

I am getting the following:
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: snoowrap refused to continue because reddit's ratelimit was exceeded. For more information about reddit's ratelimit, please consult reddit's API rules at https://github.com/reddit/reddit/wiki/API.
```

**Comment by MayorMonty** [comment]
Don't think this is an issue with snoostorm. Whenever the module is passed a Snoowrap object, it just uses it verbatim:
```javascript
return class SnooStorm {
    constructor(client) {
        this.client = isClass(client) ? client : new snoowrap(client);
    }
   // ...
}
```

The `pollTime` defaults are set so an application can use both streams and never run into ratelimit problems. In most instances, the only variable you'll need to mess with is `results:`, just based on the size of the subreddit.

**Comment by MayorMonty** [comment]
I'm gonna go ahead and close this issue.

This error you're experiencing is related to your use of `continueAfterRatelimitError` property (of course), but by default, snoowrap will wait to comply with rate limits. If you have questions about that, I think you may find better luck filing an [issue on `not-an-aardvark/snoowrap`](https://github.com/not-an-aardvark/snoowrap/issues/new)

Sorry if you're having trouble, and thanks for using `snoostorm`!
